import React from "react";
import { Layout, Carousel } from "antd";

const { Content } = Layout;
export const Home: React.FC = () => {
  return (
    <Content>
      <Carousel autoplay>
        <>
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
          TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST
        </>
        <>TEST</>
      </Carousel>
    </Content>
  );
};
